### ISSUE TITLE
Contribution guidelines request

### ISSUE THREAD

**Issue by loganvolkers** [HubSpot/jinjava#1]
This is a great open source library! Sounds like it is exactly what we might want to use for our company.

Could you add some documentation for contribution guidelines and how to get involved in this project? Or do you think that HubSpot won't be keeping this open source for very long?

**Comment by jaredstehler** [comment]
Appreciate the interest! HubSpot is committed to keeping this project open source, and we definitely welcome PR's!

Added https://github.com/HubSpot/jinjava/blob/master/CONTRIBUTING.md

**Comment by loganvolkers** [comment]
That was fast! Thanks
