### ISSUE TITLE
[range] unable to modify existing variable inside a range loop

### ISSUE THREAD

**Issue by ylacaute** [HubSpot/jinjava#1002]
This code :

```j2
{% set foo = "titi" %}

0) should be titi: {{ foo }}


{% if true %}
  {% set foo = "toto" %}
{% endif %}

1) should be toto: {{ foo }}


{% for i in range(10) %}
  {% set foo = "tutu" %}
{%- endfor -%}

2) should be tutu: {{ foo }}
```

produce this output :
```
0) should be titi: titi
1) should be toto: toto
2) should be tutu: toto
```

I think the last should be "tutu", right ?

Jinjava version 2.6.0.

**Comment by mattcoley** [comment]
This is how scopes work in Jinjava/Jinja. When you are in the `for` loop you enter a new scope, so any `set` commands are local to that new local scope. At the end of the for loop we pop that local scope from the stack.

Unfortunately the workaround involves using a dictionary to store your values. See https://stackoverflow.com/questions/9486393/jinja2-change-the-value-of-a-variable-inside-a-loop as an example.
