### ISSUE TITLE
"list" filter is not working as expected for arrays

### ISSUE THREAD

**Issue by egyedt** [HubSpot/jinjava#1013]
If you try to use the following:
`{%- set array = properties['key'].split(',')|list -%}`

Then you will get a list with only one element (the array). Instead of getting a list from the arrays element.
We should extend _list_ filter's logic to work better with object and primitive arrays as well.

**NOTE**:  this is needed since arrays does not support a lot of operations like:
 - is containing
 - is within
 - in
 - etc.

So it may happen someone want to have a list instead of an array but it is not possible with filters like _list_.

**Comment by tkindy** [comment]
Resolved in https://github.com/HubSpot/jinjava/pull/1014
