### ISSUE TITLE
Java 17.0.6 + jinjava 2.5.0 function: ".replace"

### ISSUE THREAD

**Issue by sanchoo85** [HubSpot/jinjava#1019]
After upgrading java 11 to 17 we have a problem with the replace function.
Example:
{{ "web.xyz".replace('web', 'test') }} -> teb.xyz
This works fine:
{{ "web.xyz"|replace('web', 'test') }} -> test.xyz

After upgrading java from the replace function, it takes the first character from the replace function and not the whole string.

**Comment by jasmith-hs** [comment]
This was fixed in https://github.com/HubSpot/jinjava/pull/996
And we are going to release 2.7.0 today https://github.com/HubSpot/jinjava/pull/1021
