### ISSUE TITLE
multi map convert issue

### ISSUE THREAD

**Issue by WindKn** [HubSpot/jinjava#1026]
@Test
    public void test() {
        Jinjava jinjava = new Jinjava();
        Map<String, Object> context = new HashMap<>();
        Map<String, Object> pipelineRun = new HashMap<>();
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("product-name", "aaaa");
        pipelineRun.put("parameters", parameters);
        context.put("pipelineRun", pipelineRun);
        String template = "x-{{pipelineRun.parameters.product-name}}.zip";
        String renderedTemplate = jinjava.render(template, context);
        System.out.println(renderedTemplate);
    }

expect result: x-aaaa.zip，but get x-0.zip, why

**Comment by didiercrunch** [comment]
@WindKn the issue here is that you use an hyphen (`-`) in a key name.  The expression `pipelineRun.parameters.product-name` is translated to `pipelineRun.parameters.product` minus `name`.  If you rename `product-name` to `product_name` it will work.

The below test passes.
```java
@Test
public void test() {
    Jinjava jinjava = new Jinjava();
    Map<String, Object> context = new HashMap<>();
    Map<String, Object> pipelineRun = new HashMap<>();
    Map<String, Object> parameters = new HashMap<>();
    parameters.put("product_name", "aaaa");
    pipelineRun.put("parameters", parameters);
    context.put("pipelineRun", pipelineRun);
    String template = "x-{{pipelineRun.parameters.product_name}}.zip";
    String renderedTemplate = jinjava.render(template, context);
    assertEquals(renderedTemplate, "x-aaaa.zip");
}
```
