### ISSUE TITLE
TemplateError: could not resolve function 'range', why?

### ISSUE THREAD

**Issue by tbchj** [HubSpot/jinjava#104]
when I used jinjava, i have a template file. but the template have "for i in range(2) ....",but when running this, failed. why?  donn't support "function range" ,help me...
I used jar version: 2.0.11-java7, is this merged the range function code ???
i am waiting, please .thank you

**Comment by boulter** [comment]
@tbchj can you attach a test case?

**Comment by ylacaute** [comment]
Hi, same problème here with v2.1.4

`
        Map<String, Object> env = new HashMap<>();
        String template =
                "{% for i in range(10) %}\n" +
                " - index={{ loop.index }}\n" +
                "{% endfor %}\n";
      
        String result = new Jinjava().render(template, env);`

Give  
`Could not resolve function 'range'`
