### ISSUE TITLE
add support for named parameters to filters

### ISSUE THREAD

**Issue by jaredstehler** [HubSpot/jinjava#11]
currently filters only support parameters positionally (even though we allow naming syntactically, we actually ignore the names when invoking the filter).

**Comment by boulter** [comment]
Hi Jose, I don't think we have a clear idea of how we'd do named parameters. How about starting a PR and we'll work though it there?

Thanks!

**Comment by igalarzab** [comment]
Sorry for the delay, here is the PR: #105 

Please, give some feedback when you have some free time :)
