### ISSUE TITLE
Inconsistent implementation with jinja2

### ISSUE THREAD

**Issue by halfopen** [HubSpot/jinjava#1141]
Template
`{% if a  %} 1 {% else %} 0 {% endif %}`

when a is a float number between 0 and 1, the result will be 0.

jinjava
![image](https://github.com/HubSpot/jinjava/assets/8960313/9921ec1c-cead-4902-b30f-2a6ec341d95a)
![image](https://github.com/HubSpot/jinjava/assets/8960313/80e7a3dc-2481-4e14-8b4d-ddad164f73b3)

jinja2
![image](https://github.com/HubSpot/jinjava/assets/8960313/30fb065e-4f0f-4122-ac2a-0b667d00155d)

**Comment by jasmith-hs** [comment]
This has already been fixed with https://github.com/HubSpot/jinjava/pull/857. Please ensure you're on Jinjava 2.7.0+

```java
String result = new Jinjava()
  .render("{% if a %}1{% else %}0{% endif %}", ImmutableMap.of("a", 0.3));
assertThat(result).isEqualTo("1");
```
