### ISSUE TITLE
Question: Future Plans

### ISSUE THREAD

**Issue by edeknede** [HubSpot/jinjava#1197]
Hi Community,

First of all, thank you for creating and maintaining this library. 
As a software architect, I am keen to understand the long-term vision for this library. Could you please share your plans for the next five years if exists? Specifically, I am interested in knowing:

What was the initial idea behind creating this library?
Was it primarily developed to facilitate a migration from Jinja templates, or does it have a broader scope?
Is this library intended to be a core part of your system at hubspot, or do you foresee it being phased out after fulfilling its initial purpose?

I am trying to build a pattern library that is used in a client side universe and also on the server side universe. Therefore iam searching a ssr templating library to implement a server-side component library. I really appreciate all the features it offers, especially the support for writing UI components and nesting/slotting them, which many other libraries do not support. Currently only [qute](https://quarkus.io/guides/qute) from the quarkus universe is able to do this as well. As we are in a Spring Ecosystem some boilerplate code needs to be written to make it happen. Jinjava is much more extensible and better to be integrated.

Your insights will be invaluable for us as we plan our future development efforts. For sure we could contribute to this project as well.

BTW: Do you know why the latest versions 2.7.3 of this library is not published to maven central, as it has some vulnerabilities in the dependencies. 

Thank you for your time and for all the hard work you put into this project.

Best regards

**Comment by jasmith-hs** [comment]
> What was the initial idea behind creating this library?

HubSpot's CMS used to run with python + jinja. We migrated to Java and this repo let's us continue to use jinja templates that are used for SSR with our CMS. We extend upon the functionality of Jinja/Jinjava with our markup language "HubL".



> Was it primarily developed to facilitate a migration from Jinja templates, or does it have a broader scope?

Both to be able to continue using Jinja templates in Java. We've continued to expand upon its functionality to support novel use-cases (such as eager execution), which aren't handled with Jinja. However, we have not implemented all the new features of jinja2 within jinjava.



> Is this library intended to be a core part of your system at hubspot, or do you foresee it being phased out after fulfilling its initial purpose?

It's sticking around for the long-haul at HubSpot. It's used as the core of our [HubL](https://developers.hubspot.com/docs/cms/hubl) markup language



> Do you know why the latest versions 2.7.3 of this library is not published to maven central, as it has some vulnerabilities in the dependencies.

Version 2.7.3 doesn't exist yet. It's still a snapshot. We'll likely release 2.7.3 soon and bump the version in this repo to 2.7.4-SNAPSHOT

> For sure we could contribute to this project as well.

That would be welcomed and appreciated!
