### ISSUE TITLE
Release 2.7.3

### ISSUE THREAD

**Issue by ccutrer** [HubSpot/jinjava#1198]
@jasmith-hs: it's been over 6 months since the 2.7.2 release. Can we please get a new release? #1152 is pretty critical to [openHAB](https://www.openhab.org)'s use of Jinja. Also, I believe all of the security vulnerabilities in dependencies listed on Maven Central for 2.7.2 will be resolved as well, since it doesn't appear pom.xml pins Guava to a specific version anymore. You should also probably close the other tickets asking for releases and complaining about security vulnerabilities in 2.7.0 and 2.7.1.

**Comment by jasmith-hs** [comment]
I'll work on that this week

**Comment by ccutrer** [comment]
Done! Thank you!
