### ISSUE TITLE
Disable default registered tags

### ISSUE THREAD

**Issue by robzienert** [HubSpot/jinjava#120]
I'm looking for a way to remove some of the default registered tags. For security reasons, we don't want end-users to be able to use tags like `extends`, `import` or `include`.

Would you accept a PR that adds this capability?

**Comment by robzienert** [comment]
Arrr... just noticed how this is done. Nevermind and thank you.

**Comment by ntananh** [comment]
Hey @robzienert, could you please share the way to disable it? I want to disable this `{{ }}` in my project. Thanks for your attention!
