### ISSUE TITLE
Dash In Key For Map Leads to Empty Template

### ISSUE THREAD

**Issue by Muakasan** [HubSpot/jinjava#123]
When you put a dash (-) as a key into your context map, the the key will not render in the output.  It would be nice for this to either work or throw an exception.

**Comment by hs-lsong** [comment]
Can you please clarify a bit about this issue? Are you trying to use a dash "-" as the variable for the template? Do you have a use case? Or maybe a test case? Does the python version work as you expected? Thanks.
