### ISSUE TITLE
Can not get the key in map in for loop

### ISSUE THREAD

**Issue by FieldSoft-HelloClyde** [HubSpot/jinjava#126]
**TestCase：**
`{
  "zkhost":{
    "aaa":null,
    "bbb":null,
    "ccc":null
}
`
`{%for zk in zkhost%}{{zk}}{%if not loop.last%},{%endif%}{%endfor%}`

**the result we want:**

> aaa,bbb,ccc

**in fact**

> ,,

**Comment by hs-lsong** [comment]
zk is the value of the map. If you want to get keys, use the following.
{%for zk,v in zkhost.items()%}{{zk}}{%if not loop.last%},{%endif%}{%endfor%}

**Comment by FieldSoft-HelloClyde** [comment]
thx
