### ISSUE TITLE
VariableChain does not use SimpleResolver

### ISSUE THREAD

**Issue by markus-s24** [HubSpot/jinjava#13]
Due to VariableChain doing the resolving (instead of SimpleResolver) ResourceBundles are not supported. The reflection stuff for beans, maps, collections etc. has been duplicated. Is there a reason for this or is it by accident?

**Comment by jaredstehler** [comment]
this is likely by accident, or as a relic of the project's past life as jangod. I can look into completely removing VariableChain (I'd love to reduce the code and rely much more on the robust juel library when possible), and definitely welcome PRs!

**Comment by markus-s24** [comment]
Sure, but I don't know if I find the time to do it.

BTW I did an Ant integration for jinjava: https://github.com/shopping24/jinja4ant

**Comment by markus-s24** [comment]
See PR #15
