### ISSUE TITLE
Should a for-loop fail if `failOnUnknownTokens` is set?

### ISSUE THREAD

**Issue by danielpeach** [HubSpot/jinjava#139]
From the name of the config flag `failOnUnknownTokens`, I expected rendering
``` {% for zone in zones %} ... {% endfor %}``` 
to fail if `zones` is not defined in the bindings.

I can implement the behavior if that's a reasonable expectation. If it is, are there other tags that should respect that flag?

**Comment by InboundFrog** [comment]
We're seeing a similar issue with defaulting values. ie
```
{{ not.a.defined.variable | default("something") }}
```
Will use the default if `failOnUnknownTokens` is `true`, but
{{ not.a.defined.variable }}
will fail.

Which actually seems somewhat reasonable. But, for our use-case, we're testing templates that will eventually be generated by Ansible and the Python Jinja2 renderer. Using the Python renderer, both cases above would fail.

So, should `failOnUnknownTokens` be very strict? Or is this something that would need another flag of some kind?
