### ISSUE TITLE
datetimeformat filter on NULL dates

### ISSUE THREAD

**Issue by zepernick** [HubSpot/jinjava#149]
I am not sure if this is a bug or by design, but I thought I would point it out.  The datetimeformat is returning the format of today's date if the date the filter was ran on is null.  I looked at the [doc here](http://designers.hubspot.com/docs/hubl/hubl-supported-filters) and it does not give any indication of the intended functionality.

The filter is using the Functions.getDateTimeArg() which is causing this behavior

```java 
private static ZonedDateTime getDateTimeArg(Object var) {

    ZonedDateTime d = null;

    if (var == null) {
      d = ZonedDateTime.now(ZoneOffset.UTC);
    } else if (var instanceof Number) {
      d = ZonedDateTime.ofInstant(Instant.ofEpochMilli(((Number) var).longValue()), ZoneOffset.UTC);
    } else if (var instanceof PyishDate) {
      d = ((PyishDate) var).toDateTime();
    } else if (var instanceof ZonedDateTime) {
      d = (ZonedDateTime) var;
    } else if (!ZonedDateTime.class.isAssignableFrom(var.getClass())) {
      throw new InterpretException("Input to function must be a date object, was: " + var.getClass());
    }

    return d;
  }
```

**Comment by boulter** [comment]
Thanks for noting that @zepernick. I agree it's a little odd, but it would certainly break existing code if we were to change the default.

I updated the documentation to note the behavior.
