### ISSUE TITLE
Support for enumerate()

### ISSUE THREAD

**Issue by stephenh0312** [HubSpot/jinjava#155]
Currently, the following statement fails even though I tried defining the enumerate method in java to return my own "Tuple" class and a "Map" object.

{% for index, object in enumerate(list) %}

I was able to write and define an ELFunction which was accepted and runs without failing. However, after the template is rendered, the replacement for "index" and "object" are just null.

What should/can I return as a result of "enumerate" for the above statement to work with jinjava?
        
jinjava.getGlobalContext().registerFunction(
                new ELFunctionDefinition("", "enumerate", JinjavaHelpers.class, "enumerate", List.class));

public static <X> List<Map<Integer,X>> enumerate(List<X> list_in) {
        List<Integer> nums = new ArrayList<Integer>(list_in.size());
        for (int x = 0; x < list_in.size(); x++) { 
            nums.add(Integer.valueOf(x));
        }

        return zip(nums, list_in);
    }
    
    public static <X,Y> List<Map<X,Y>> zip(List<X> list_a, List<Y> list_b) {
        Iterator<X> xiter = list_a.iterator();
        Iterator<Y> yiter = list_b.iterator();

        List<Map<X,Y>> result = new LinkedList<Map<X,Y>>();

        while (xiter.hasNext() && yiter.hasNext()) {
            Map<X,Y> myMap = new HashMap<X,Y>();
            myMap.put(xiter.next(), yiter.next());
            result.add(myMap);
        }

        return result;
    }

**Comment by boulter** [comment]
Hi @stephenh0312, can you use `items()`?

```
{% for key, value in dictionary.items() %}
    {{ key }}: {{ value }}
{% endfor %}
```
If not, could you create a PR with what you're trying to do so we can help?
