### ISSUE TITLE
add support for trim_blocks, lstrip_blocks

### ISSUE THREAD

**Issue by cosmin** [HubSpot/jinjava#17]
Jinja itself provides two useful options `trim_blocks` and `lstrip_blocks` for changing the behavior of whitespace preservation in the output. Quoting from the documentation:

If an application configures Jinja to `trim_blocks`, the first newline after a template tag is removed automatically (like in PHP). The `lstrip_blocks` option can also be set to strip tabs and spaces from the beginning of a line to the start of a block. (Nothing will be stripped if there are other characters before the start of the block.)

With both `trim_blocks` and `lstrip_blocks` enabled, you can put block tags on their own lines, and the entire block line will be removed when rendered, preserving the whitespace of the contents. 

These options are particularly important when using this to render things other than HTML where whitespace itself can be significant (for example, Markdown).

**Comment by cosmin** [comment]
I looked into this a bit more, and I think it's going to be interesting to implement this in this project. Jinja2 itself accomplishes this because it uses regular expressions to parse blocks, and it modifies the regular expression for the start and end of a block based on the values of `trim_blocks` and `lstrip_blocks`. 
Meanwhile `jinjava` does this using a scanner, which I think makes this harder to accomplish.

In theory `trim_blocks` could be easily supported by continuing to swallow a newline following the end of a block, but even that is tricky, because you only want blocks `{% ... %}` to get this behavior, and not expressions `{{ .. }}`, so that alone will requires some work.

However `lstrip_blocks` becomes more interesting. As far as I can tell, the TextNode will get all of the whitespace prefixing a block, so there is not much we can do during parsing, without having to either look ahead and see if there will be a block starting on this line, or by going back and altering the text node preceding a block.

In either case I think this will require some work to get right. However, it's still a very critical feature when using this project for whitespace sensitive items. For example, Ansible uses Jinja2 to parse its templates, and it has `trim_blocks` enabled by default. There is also a feature request to turn on `lstrip_blocks` by default because of all of the issues introduced by not having that turned on. So clearly these are important features at least for some use cases, although I can understand that it probably doesn't apply to what HubSpot needs.

**Comment by jaredstehler** [comment]
Agreed that this sounds like a tricky one to implement, but we should be able to come up with a comprehensive test suite for it. I should hopefully get a chance to work on it this week.

**Comment by jaredstehler** [comment]
Implemented as two new parameters on ```JinjavaConfig```... you can enable like:

```
JinjavaConfig.newBuilder()
  .withLstripBlocks(true)
  .withTrimBlocks(true)
  .build()
```

206ca3d
