### ISSUE TITLE
Is jinjava java 9 compatible? 

### ISSUE THREAD

**Issue by gabeki** [HubSpot/jinjava#182]
Hi,

Is jinjava java 9 compatible?  This test passed with java 8 but failed in java 9.   Is there a workaround?

Using jinjava 2.4.

```
    @Test
    public void testPlusD() {
        final class PlusD implements Filter {
            @Override
            public Object filter(Object var, JinjavaInterpreter interpreter, String... args) {
                return var + "D";
            }

            @Override
            public String getName() {
                return "plus_d";
            }
        }

        Jinjava jinjava = new Jinjava();
        jinjava.getGlobalContext().registerFilter(new PlusD());
        final String output = jinjava.render("{{ 'ABC' | plus_d }}", Collections.emptyMap());
        assertEquals("ABCD", output);
    }
```

Caused by: com.hubspot.jinjava.interpret.FatalTemplateErrorsException: TemplateSyntaxException: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/hubspot/jinjava/lib/filter/Filter. Method lambda$filter$3(Ljava/lang/Object;)Ljava/lang/String; at index 53 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
        at com.hubspot.jinjava.Jinjava.render(Jinjava.java:154)

**Comment by gabeki** [comment]
Maybe we need to review this [line](https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/lib/filter/Filter.java#L53)?  Thanks.

**Comment by boulter** [comment]
@gabeki I couldn't reproduce your issue, but I removed the method reference anyway. Do you want to pull down https://github.com/HubSpot/jinjava/pull/186 and see if it resolves your issue?

**Comment by gabeki** [comment]
👍 your branch works.

**Comment by bezineb5** [comment]
Actually, I have the same issue on JDK10 than @gabeki using version 2.4.4, where this fix is included, using the maven artefact. However, when build from source, using a recent JDK 10, it works fine.
I feel that the issue is that the version on maven is compiled with an old JDK which does not produce bytecode compatible with JDK10, which is more strict that java 8 in bytecode checks.

How do you build it for Maven?
