### ISSUE TITLE
getting class not found for `com/google/common/base/MoreObjects`

### ISSUE THREAD

**Issue by sar009** [HubSpot/jinjava#185]
when installing latest jinjava as 
```
<dependency>
    <groupId>com.hubspot.jinjava</groupId>
    <artifactId>jinjava</artifactId>
    <version>2.4.0</version>
  </dependency>
```
I am getting class `com/google/common/base/MoreObjects` not found. I had to upgrade guava
```
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>24.1-jre</version>
</dependency>
```

my guava version was 21.0

**Comment by boulter** [comment]
@sar009 do you have the full stack trace or compilation message? There's no references to `MoreObjects` in the jinjava source.

**Comment by ebuildy** [comment]
Of course ! 

As you can see : https://google.github.io/guava/releases/20.0/api/docs/com/google/common/base/Objects.html

```
Objects.ToStringHelper
Deprecated. 
Use MoreObjects.ToStringHelper instead.
```

I guess the legacy code call this method from Guava@v20
