### ISSUE TITLE
jinjava render to 0

### ISSUE THREAD

**Issue by pingc-sh** [HubSpot/jinjava#198]
Hi 

I have json config(convert to java map when doing jinjava rendering)
{
  "yaml-j2-config": [
    {
      "template-name": "hwim_lease_alert",
      "topic-name": "hwim_lease"
    },
    {
      "template-name": "nimbus-quota-usage-alert",
      "topic-name": "topic_nimbus_vm_usage",
    }
  ]
}

and j2 file:

{% for config in yaml-j2-config %}
  - id: "DataStringScheme.{{ config.template-name }}"
    className: "com.vmware.nimbus.storm.common.DataStringScheme"
    constructorArgs:
      - {{ config.template-name }}
......

the render result is:

  - id: "DataStringScheme.0"
    className: "com.vmware.nimbus.storm.common.DataStringScheme"
    constructorArgs:
      - 0

why it renders to 0?

**Comment by boulter** [comment]
@pingc-sh can you post some runnable code so we can try to reproduce this?

**Comment by pingc-sh** [comment]
Hi Jeff
Thanks for the reply, here is the details:

1. json config which convert to map:
{
    "yaml-j2-config": [
        {
            "template-name": "hwim_lease_alert",
            "topic-name": "hwim_lease"
        },
        {
            "template-name": "nimbus-quota-usage-alert",
            "topic-name": "topic_nimbus_vm_usage"
        }
    ]
}

2. j2 file:
---
name: ${topology-name}

components:
{% for config in yaml-j2-config %}
  - id: "DataStringScheme.{{ config.template-name }}"
    className: "com.vmware.nimbus.storm.common.DataStringScheme"
    constructorArgs:
      - {{ config.template-name }}

  - id: "SchemeAsMultiScheme.{{ config.template-name }}"
    className: "org.apache.storm.spout.SchemeAsMultiScheme"
    constructorArgs:
      - ref: "DataStringScheme.{{ config.template-name }}"

  - id: "kafkaSpoutConfig.{{ config.template-name }}"
    className: "com.vmware.nimbus.storm.common.NimbusKafkaSpoutConfig"
    constructorArgs:
      - ${zookeeper-servers}
      - {{ config.topic-name }}
      - ${topology-name}
      - true
    properties:
      - name: "scheme"
        ref: "SchemeAsMultiScheme.{{ config.template-name }}"
      - name: "stateUpdateIntervalMs"
        value: 5000
{% endfor %}

3. java code with jinjava:
        // render yaml file from j2 file if needed
        String yaml_file_string;
        Map<String, Object> map = JsonUtil.jsonStringToMap(settings.toJsonString()); // this load json config
        if (map.get("yaml-j2-config") != null) {
            Path j2_path = Paths.get("xx.yaml.j2");  // this load js file
            String j2_template = new String(Files.readAllBytes(j2_path));

            Jinjava jinjava = new Jinjava(new JinjavaConfig());
            String yaml_template = jinjava.render(j2_template, map);  // after render it generates 0
            ......
        } else {}

4. jinjava output:
---
name: ${topology-name}

components:

  - id: "DataStringScheme.0"
    className: "com.vmware.nimbus.storm.common.DataStringScheme"
    constructorArgs:
      - 0

**Comment by pingc-sh** [comment]
Hi, is there any update? is this really a bug or my config issue?

**Comment by boulter** [comment]
@pingc-sh could you submit a small, runnable piece of code that demonstrates your issue? Otherwise it's very difficult to reproduce.
