### ISSUE TITLE
Documentation for registering a new filter is wrong

### ISSUE THREAD

**Issue by pranildasika** [HubSpot/jinjava#22]
The steps mentioned in the README.md to add a custom filter dont seem to be valid anymore.

The following line:
jinjava.getFilterLibrary().addFilter(new MyAwesomeFilter());
should be 
jinjava.getGlobalContext().registerFilter(new MyAwesomeFilter());

**Comment by jaredstehler** [comment]
good catch, thanks! 60c544ea09f49aecf6b5a09a70b71720d743948a
