### ISSUE TITLE
Issue with java 9/10

### ISSUE THREAD

**Issue by bezineb5** [HubSpot/jinjava#228]
Hello,
I'm reopening issue #182 as it seems that the version published on the maven repository is not java 9 and 10 compatible.
When using the version 2.4.5 from maven (it was the same with previous versions), I get errors like that:
`TemplateError{severity=FATAL, reason=SYNTAX_ERROR, item=OTHER, message='TemplateSyntaxException: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/hubspot/jinjava/lib/filter/Filter. Method lambda$filter$0(Ljava/lang/Object;)Ljava/lang/String; at index 53 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef', fieldName=' count|default(1) ', lineno=1, startPosition=-1, scopeDepth=1, category=UNKNOWN, categoryErrors=null}
`
However, when I check out the repository and compile the library locally, everything works fine.

What is your compilation process to publish the jar? Could it be that the JDK you're using generates bytecode which is not java 9 compatible? They have stricter checks apparently.

Thanks!

**Comment by flozano** [comment]
Given that JDK11 is now the "LTS" version of Java, is there any chance of revisiting this?

**Comment by boulter** [comment]
@bezineb5, @flozano can you try adding 2.4.12-SNAPSHOT as your jinjava version in your pom and see if that fixes the issue? If it does, I'll do a release.

**Comment by bezineb5** [comment]
@boulter I confirm it works! Thanks a lot, I think you can do a release.

**Comment by flozano** [comment]
Thanks! I couldn't try myself yet

**Comment by boulter** [comment]
2.4.12 has been released.
