### ISSUE TITLE
Filter ipaddr always return false -> returns nothing

### ISSUE THREAD

**Issue by Devl11** [HubSpot/jinjava#236]
Hi,
I am trying to use the ipaddr filter but it does not return any value.

``` java
Jinjava jinjava = new Jinjava();
String template = "hello {{ testvar | ipaddr }}";

HashMap values = new HashMap();
values.put("testvar", "127.0.0.1");
jinjava.render(template, values);  
```

It only returns "hello ". 
Am I missing something?

**Comment by mattcoley** [comment]
`ipaddr` has not been implemented yet in jinjava.

**Comment by Devl11** [comment]
Well thats explains it!
What I really wanted was to use ``ìpaddr('prefix')```, does jinjava have any similar filter?

**Comment by mattcoley** [comment]
Shouldn't take too long to add the `ipaddr` filter.

**Comment by Devl11** [comment]
Is it possible to add the ```ipaddr('prefix')``` etc to get the prefix from an ip? 
Like ```{{ '192.0.2.0/24' | ipaddr('prefix') }} ``` which return 24

**Comment by MikaelMollberg** [comment]
> Is it possible to add the `ipaddr('prefix')` etc to get the prefix from an ip?
> Like `{{ '192.0.2.0/24' | ipaddr('prefix') }}` which return 24

That would be great!
