### ISSUE TITLE
Jinjava unexpected DEBUG messages in console

### ISSUE THREAD

**Issue by slicednet** [HubSpot/jinjava#255]
I have just added jinjava into my gradle project today but I'm getting these messages in console. Tried forcing jinjava package as info in log4j2 but no luck. The generated string from render() is working however I don't understand why these DEBUG messages are showing up. Any idea how to disable these messages or what's causing these to show up? Appreciate any help/response. Thanks!
```
...
22:42:12.760 [qtp929776179-23] DEBUG jinjava - ExpTestLibrary: Registered even
22:42:12.760 [qtp929776179-23] DEBUG jinjava - ExpTestLibrary: Registered iterable
22:42:12.760 [qtp929776179-23] DEBUG jinjava - ExpTestLibrary: Registered lower
22:42:12.760 [qtp929776179-23] DEBUG jinjava - ExpTestLibrary: Registered mapping
...
22:42:12.779 [qtp929776179-23] DEBUG jinjava - FilterLibrary: Registered reject
22:42:12.779 [qtp929776179-23] DEBUG jinjava - FilterLibrary: Registered select
22:42:12.779 [qtp929776179-23] DEBUG jinjava - FilterLibrary: Registered selectattr
...
22:42:12.925 [qtp929776179-23] DEBUG jinjava - FunctionLibrary: Registered :today
22:42:12.925 [qtp929776179-23] DEBUG jinjava - FunctionLibrary: Registered :super
...
22:42:12.927 [qtp929776179-23] DEBUG jinjava - FunctionLibrary: Registered fn:immutable_list
22:42:12.954 [qtp929776179-23] DEBUG jinjava - <!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
...
```

Here's my details:
* build.gradle dependencies
compile 'com.hubspot.jinjava:jinjava:2.4.11'
* in java code, I just simply called Jinjava and then render()
```java
    protected String replaceVars(String pageContent, Map<String, Object> pageVars) {
        Jinjava jinJava = new Jinjava();
        return jinJava.render(pageContent, pageVars);
    }
```
* in log4j2.xml
```xml
  <Loggers>
    <Root level="info">
      <AppenderRef ref="CONSOLE"/>
    </Root>
    <Logger name="com.hubspot.jinjava" level="info">
      <AppenderRef ref="CONSOLE" />
    </Logger>
  </Loggers>
```

**Comment by boulter** [comment]
hi @slicednet, the logger name is "jinjava". Can you try replacing "com.hubspot.jinjava" with "jinjava" in your `log4j2.xml` file?

**Comment by slicednet** [comment]
Changing to jinjava in log4j2x.xml did not help.

After investigating and reading jinjava sources, I found out SimpleLibrary abstract class which is the source of the above messages. This class defines ENGINE_LOG which uses slf4j logger. However, the framework I used is log4j2. What I just tried is to use `org.apache.logging.log4j:log4j-slf4j-impl:2.11.1`
and apply log4j2.properties in classpath with
```
name=config
appenders=console
appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
rootLogger.level=info
rootLogger.appenderRefs=stdout
rootLogger.appenderRef.stdout.ref=STDOUT
```
and it worked. The above jinjava debug messages are no longer displayed.

Thanks @boulter for the response which gave me some idea to find out what logging framework jinjava is using.

**Comment by nodermatt** [comment]
Hi @slicednet @boulter I'm having the same problem in a Jersey application I'm writing. Do you have any idea to disable the DEBUG messages without including Log4J? I'm using Java's logging and prefer to refrain from including a dependency to silent Jinjavas output.

From what I can tell is that the rootLogger.level instruction overwrites the default logging level from JinJava, right?

    rootLogger.level=info

I actually opened a SO post on the subject: https://stackoverflow.com/questions/54666049/disable-debug-log-in-jinjava

Cheers
