### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by dougalg** [HubSpot/jinjava#26]
```
JinjavaConfig config = new JinjavaConfig();
config.setResourceLocator(new MyCustomResourceLocator());

Jinjava jinjava = new Jinjava(config);
```

Should read

```
Jinjava jinjava = new Jinjava(config);
jinjava.setResourceLocator(new MyCustomResourceLocator());
```

**Comment by dougalg** [comment]
Also it's not clear what a resourcelocator should do?

**Comment by jaredstehler** [comment]
Thanks for the heads up! A ```ResourceLocator``` is responsible for retrieving a template as a string from a given path, and is used by the ```{% include %}``` and ```{% import %}``` tags. You can specify a custom ```ResourceLocator``` if you have templates in places other than classpath or filesystem, such as in a database.

**Comment by jaredstehler** [comment]
https://github.com/HubSpot/jinjava/commit/a47d18025e9751ac2e36a8d7e606cfa6d70b2991

**Comment by dougalg** [comment]
Thanks for the quick fix!
