### ISSUE TITLE
No filter to intersect two lists

### ISSUE THREAD

**Issue by jfudman** [HubSpot/jinjava#261]
Currently there is no way to get the intersection of 2 lists (example below).
```jinja2
{% set list1 = [ 'a', 'b', 'c' ] %}
{% set list2 = [ 'c', 'd' ] %}
{{ list1 | intersect(list2) }} {# would output ['c'] #}
```

See the[ set theory filters for ansible](https://ansible-docs.readthedocs.io/zh/stable-2.0/rst/playbooks_filters.html#set-theory-filters) as a good example.

### A more elaborate example below
```{% set section_active = false %}
{% set tags = content.tagList|map('slug') %}
{% set list2 =  [ 'foo','poo', 'doo', 'boo' ] %}
{% set joined =  tags|intersect(list2) %}
{% unless joined == [] %}
  {% set section_active = true %}
{% endunless %}
```

**Comment by mattcoley** [comment]
Shouldn't be too hard to support those set functions.
