### ISSUE TITLE
Nested variable support

### ISSUE THREAD

**Issue by dougalg** [HubSpot/jinjava#27]
Nested variables don't seem to be working as expected ie: in my template

```{{ date.from }}```

and rendering with something like this (using Scala)

```
val m = immutable.HashMap(
      "date" -> immutable.HashMap(
        "from" -> "1451865600000",
        "to" -> "1452038400000"
      )
  )
jinjava.render(template, mapAsJavaMap(m))
```

Renders fine, but the value is not being printed into the output.

Is this just not part of your implementation of Jinja?

**Comment by jaredstehler** [comment]
what ended up being the issue?

**Comment by namingbe** [comment]
DenverCoder9 moment right here.

Encountered the same issue, it only recognised Java's `HashMap`, and quietly failed to resolve all other map types that I've tried passing.
