### ISSUE TITLE
com.hubspot.jinjava.interpret.FatalTemplateErrorsException: TemplateSyntaxException: Could not resolve function 'namespace'

### ISSUE THREAD

**Issue by pastorcmentarny** [HubSpot/jinjava#274]
Good Morning/Afternoon/Evening/Night!

I am working on Java project that is using existing templates written uses jinja as a project was written in Python.

During my compatibility check, I hit a problem as one of our template use namespace and this throw exception:

com.hubspot.jinjava.interpret.FatalTemplateErrorsException: TemplateSyntaxException: Could not resolve function 'namespace'

I assume I see this error because the namespace is not implemented yet as namespace was introduced in jinja2 2.10 which is lasted version. (i search about namespace here: http://jinja.pocoo.org/docs/2.10/templates/)

If this feature is missing, do you have any plans to add it?

or I wrong and a feature is implemented?
If yes, then I am happy to share problematic part of the template to determine if a problem with the template or with the library.

Let me know if you need more details.

Thank you very much

**Comment by boulter** [comment]
Hi @pastorcmentarny, you are correct. Namespaces aren't implemented in Jinjava yet, but contributions are welcome!

**Comment by pastorcmentarny** [comment]
@boulter I was thinking to contribute to this project.

I forked a project and I look into it.
I came with some solution idea which I would like to share with to validate my idea and point me in the right direction if I misunderstood something.

According to jinja2, the namespace is a global function that is used to " to allow carrying value from within a loop body to an outer scope"
I was thinking about creating a class as a container (let's call this "Namespace container" for now)  that will hold these variables in JinjaInterpreter or JinjaInterpreter's context.

I would like to add a method in Functions class and add it to FunctionLibrary. This method will be a response to put a value to key/value (name/value) "Namespace container"  (that will override any existing value if already exist)

In order to get the value, it will look to a local variable first and if not then it will look into "Namespace container" for variable and return it if found.

Is this design idea sound good for you?
I will appreciate your feedback.

**Comment by boulter** [comment]
Sounds like a good plan!

**Comment by mattkindy-praetorian** [comment]
With existing functionality, I was able to hack something that works pretty well (excluding setting arguments in the constructor... yet)

Modify (or extend and reregister) `SetTag` to use 
```
private Object assign(@NonNull final String assignedExpression,
                      final Object toAssign,
                      final JinjavaInterpreter interpreter) {
  final Context context = interpreter.getContext();
  if (assignedExpression.contains(".")) {
    final String[] namespaceWithAttribute = assignedExpression.split("\\.", 2);
    final String namespaceVar = namespaceWithAttribute[0];
    final String attributeVar = namespaceWithAttribute[1];
    final Map<String, Object> namespace = (Map<String, Object>) context.get(namespaceVar);
    namespace.put(attributeVar, toAssign);
    return context.put(namespaceVar, namespace);
  }
  return context.put(assignedExpression, toAssign);
}
```

and register an `ELFunctionDefinition` 
```
private static final ELFunctionDefinition NAMESPACE_FN_DEF =
    new ELFunctionDefinition("", "namespace", JinjaEngine.class, "jinjaNamespace", String[].class);

private static Map<String, Object> jinjaNamespace(final String... args) {
    return new HashMap<>();
 }

jinjava
      .getGlobalContext()
      .registerFunction(NAMESPACE_FN_DEF);
```

**Comment by mattkindy-praetorian** [comment]
Yeah, here we go
```
private static final ELFunctionDefinition NAMESPACE_FN_DEF =
    new ELFunctionDefinition("", "namespace", JinjaEngine.class, "jinjaNamespace", NamedParameter[].class);

/**
 * @see JinjaEngine#NAMESPACE_FN_DEF
 */
private static Map<Object, Object> jinjaNamespace(final NamedParameter... args) {
  final HashMap<Object, Object> namespace = new HashMap<>();
  Arrays
    .stream(args)
    .forEach(namedArg -> namespace.put(namedArg.getName(), namedArg.getValue()));
  return namespace;
}
```
