### ISSUE TITLE
video_player need loop, autoplay, muted options

### ISSUE THREAD

**Issue by jfudman** [HubSpot/jinjava#322]
The `{% video_player %}` tag needs more options. I am note sure if these requested options are missing by design... but since most of them are available via [vidyard's API](https://developer.vidyard.com/), I am requesting them.

I propose adding:

- `loop_playback=True|False`,
- `autoplay=True|False`
- `mute_onload=True|False`
- and maybe even `controls=True|False`?

Wistia provides these options as well.

**Comment by mattcoley** [comment]
This is an internal HubL tag so I am copying this to an internal issue and closing.
