### ISSUE TITLE
How to analyze the java function with HashMap parameters?

### ISSUE THREAD

**Issue by ruozhixian** [HubSpot/jinjava#324]
I want to provide the function:

`jinjava.getGlobalContext().registerFunction(new ELFunctionDefinition("", "tasks", Function.class, "tasks", HashMap.class));`

to analyze the jinja sentence:

`all_tasks_in_error_jinja: "{{ tasks({ name: 'Tom', id: 'one'}) }}"`

However, it seems that jinjava just parses the parameters as com.hubspot.jinjava.objects.collections.PyMap but not HashMap,

`Exception in thread "main" com.hubspot.jinjava.interpret.FatalTemplateErrorsException: Cannot coerce '{name=Tom, id=one}' of class com.hubspot.jinjava.objects.collections.PyMap to class java.util.HashMap (incompatible type)`

and the java function cannot be executed correctly.

**Comment by boulter** [comment]
Hi @ruozhixian, you're right that Jinjava uses PyMaps. It still implements Map though, so you could just do something like `new HashMap(yourPyMap)`
