### ISSUE TITLE
Add support for disabling features

### ISSUE THREAD

**Issue by btiernay** [HubSpot/jinjava#36]
It would be nice to be able to allow users to disable certain template features. One use case would be to disable looping, extensions, etc. to offer an environment similar to what Ansible does for its YAML files. From http://docs.ansible.com/ansible/playbooks_variables.html:

> ansible allows Jinja2 loops and conditionals in templates, but in playbooks, we do not use them. Ansible playbooks are pure machine-parseable YAML. This is a rather important feature as it means it is possible to code-generate pieces of files, or to have other ecosystem tools read Ansible files. Not everyone will need this but it can unlock possibilities.

It looks like this should be possible by allowing on `Context` that allows setting the following:

https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/interpret/Context.java#L69-L72

And then allowing a constructor on `Jinjava` that takes a `Context`:

https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/Jinjava.java#L82

Alternatively, the `JinjavaConfig` could encapsulate the `Context` dependencies`. 

I would be happy to add PR if this sounds reasonable.

**Comment by jaredstehler** [comment]
Sounds interesting. Would we simply disable whole tags, like `{% for ... %} ... {% endfor %}` would resolve to `""`?

**Comment by btiernay** [comment]
I was hoping that they would be passed through, as is. Alternatively it could warn or fail, but I think this would be harder to implement.

The reason for the feature request is that I am building a system very similar to Ansible, and I agree with their philosophy here. Brace expressions for YAML, and full Jinja2 for templates. This would help me build such a system in Java.

**Comment by jaredstehler** [comment]
I think I follow. If you open a PR I'll be able to visualize it and comment further.

**Comment by btiernay** [comment]
Will do, thanks!

**Comment by boulter** [comment]
Fixed via https://github.com/HubSpot/jinjava/pull/83
