### ISSUE TITLE
Add bool filter

### ISSUE THREAD

**Issue by jhaals** [HubSpot/jinjava#38]
I'm using this library to template files from an api where all values are strings and I wonder if you would be open to add a `bool` filter that would convert a true/false string to a boolean. I'm happy to submit a PR if you think it's suiting. This is what ansible does in their [playbook filters](http://docs.ansible.com/ansible/playbooks_filters.html#other-useful-filters).

**Comment by jaredstehler** [comment]
yeah that sounds ok to me. we do have a similar construct already with the expression test `var is truthy`, which delegates to `ObjectTruthValue` for determining the boolean value of a variable (https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/util/ObjectTruthValue.java#L27). This currently only checks a string for `"false"`, however, so a new filter which explicitly uses `org.apache.commons.lang3.BooleanUtils.toBoolean(str)` makes sense.
