### ISSUE TITLE
Filters don't seem to work

### ISSUE THREAD

**Issue by xnaveira** [HubSpot/jinjava#39]
Hi, trying to use filters I get the following error:

```
com.hubspot.jinjava.interpret.FatalTemplateErrorsException: TemplateError{severity=FATAL, reason=EXCEPTION, message=InterpretException: Error resolving expression [testvar | upper]: IllegalArgumentException: wrong number of arguments, fieldName=null, lineno=1}
```

This is running:

```
Jinjava jinjava = new Jinjava(new JinjavaConfig());
String template = "hello {{ testvar | upper }}";
jinjava.render(template, ImmutableMap.of("testvar", "stranger")));
```

Running with no filters works fine.

I've checked with a colleague that's using jinjava in another project and he seems to be getting the same error.

**Comment by jaredstehler** [comment]
which version are you using? I wasn't able to reproduce on the main branch.

**Comment by xnaveira** [comment]
We're using 2.1.0 fetched via Maven.

**Comment by jaredstehler** [comment]
I am still unable to reproduce..

```
import com.google.common.collect.ImmutableMap;
import com.hubspot.jinjava.Jinjava;
import com.hubspot.jinjava.JinjavaConfig;
import com.hubspot.jinjava.interpret.RenderResult;

public class Issue39 {

  public static void main(String[] args) {
    Jinjava jinjava = new Jinjava(new JinjavaConfig());
    String template = "hello {{ testvar | upper }}";

    RenderResult result = jinjava.renderForResult(template, ImmutableMap.of("testvar", "stranger"));
    System.out.println(result.getErrors());

    System.out.println(jinjava.render(template, ImmutableMap.of("testvar", "stranger")));
  }
}
```

produces following output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[]
hello STRANGER
```

with pom dep:
```
    <dependency>
      <groupId>com.hubspot.jinjava</groupId>
      <artifactId>jinjava</artifactId>
      <version>2.1.0</version>
    </dependency>
```

**Comment by jaredstehler** [comment]
Can you post the output of `mvn dependency:tree`?

**Comment by xnaveira** [comment]
I just created an standalone project and get the same output as you. 

The problem appears when trying to use jinjava inside a dropwizard project. Let me gather some more data and get back to you.

**Comment by zepernick** [comment]
I am experiencing the same problem.  You can pass a empty parameter to the filter and it resolves it.  I opened a report before I realized this was the same thing.

https://github.com/HubSpot/jinjava/issues/43

Here is my dependency tree from mvn


[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ StrutsPlay ---
[INFO] com.hs:StrutsPlay:jar:1.0-SNAPSHOT
[INFO] +- org.apache.struts:struts2-core:jar:2.5-BETA2:compile
[INFO] |  +- org.freemarker:freemarker:jar:2.3.22:compile
[INFO] |  +- ognl:ognl:jar:3.0.11:compile
[INFO] |  |  \- javassist:javassist:jar:3.11.0.GA:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.3:compile
[INFO] |  +- commons-fileupload:commons-fileupload:jar:1.3.1:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  +- asm:asm:jar:3.3:compile
[INFO] |  \- asm:asm-commons:jar:3.3:compile
[INFO] |     \- asm:asm-tree:jar:3.3:compile
[INFO] +- org.apache.struts.xwork:xwork-core:jar:2.3.20.1:compile
[INFO] |  +- org.ow2.asm:asm:jar:5.0.2:compile
[INFO] |  \- org.ow2.asm:asm-commons:jar:5.0.2:compile
[INFO] |     \- org.ow2.asm:asm-tree:jar:5.0.2:compile
[INFO] +- com.hubspot.jinjava:jinjava:jar:2.1.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] |  +- com.google.guava:guava:jar:17.0:compile
[INFO] |  +- org.javassist:javassist:jar:3.18.2-GA:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.8.1:compile
[INFO] |  +- de.odysseus.juel:juel-api:jar:2.2.7:compile
[INFO] |  +- de.odysseus.juel:juel-impl:jar:2.2.7:compile
[INFO] |  +- de.odysseus.juel:juel-spi:jar:2.2.7:runtime
[INFO] |  \- com.google.code.findbugs:annotations:jar:3.0.0:compile
[INFO] +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  \- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] +- org.apache.commons:commons-collections4:jar:4.1:compile
[INFO] \- javax.servlet:servlet-api:jar:2.3:provided

**Comment by jaredstehler** [comment]
I don't think its the cause of this issue but there are two conflicting `javassist` libs on your classpath

**Comment by zepernick** [comment]
good catch, thanks for the heads up

**Comment by zepernick** [comment]
I created a new java project and was not able to reproduce the error with a test case.  It appears to have something to do with the Struts2 project I have it in.  I have created a custom Struts 2 result that runs the JinJava Interpreter and outputs the result.

It is just a test project and I have attached it here if you are interested in taking a look.  I will keep looking to see if I can figure out the conflict.  It is something that Struts is doing and not the mere fact that it is on the classpath.  I tried putting it on the classpath of my java project and it still worked okay.
[StrutsPlay.zip](https://github.com/HubSpot/jinjava/files/169877/StrutsPlay.zip)

**Comment by zepernick** [comment]
The real issue, for me anyway, is that I have this running on Tomcat 9 which provides a 3.0 el-api implementation.  JinJava is depending on juel-api-2.2.7 which is an implementation of the 2.2 spec.  I removed the el-api.jar from the tomcat lib and replaced it with juel-api-2.2.7 which solved the problem.  

Tomcat 7 is the latest release that provides a 2.2 implementation.  I have not tested with that version to see if JinJava would run okay without swapping in the juel-api.

**Comment by jaredstehler** [comment]
Ah, interesting. Wonder if we were to shade-relocate the juel el packages in the jinjava library jar if that would fix the conflict..?

**Comment by zepernick** [comment]
very interesting thought.  I will check into that, good idea!

**Comment by zaycev** [comment]
Had a similar issue in dropwizard project. Solved by excluding `javassist` and `javax.el`:

```
<dependency>
    <groupId>io.dropwizard</groupId>
    <artifactId>dropwizard-core</artifactId>
    <version>${io.dropwizard.version}</version>
    <exclusions>
        <!-- Conflicts with jinjava -->
        <exclusion>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.el</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
