### ISSUE TITLE
Need information on Jinjava Thread-safety

### ISSUE THREAD

**Issue by rsheldon** [HubSpot/jinjava#391]
Can you please describe how thread-safe Jinjava is (and perhaps document it?) and what the correct usage pattern is for current rendering. ie What objects can I share between threads, and which can I not?

e.g. can I create on Jinjava engine once on app startup,  and then call render from multiple threads concurrently (eg rendering content for multiple concurrent requests in a webapp).

**Comment by mattcoley** [comment]
Jinjava uses a ThreadLocal stack of interpreters so it is safe to share one `Jinjava` object across threads as each interpreter will be isolated to a single thread. If you are sharing objects between render contexts then you should ensure that those objects are thread-safe.

**Comment by mattcoley** [comment]
You can inject a singleton Jinjava object with any custom configuration and call one of the render methods `render`, `renderForResult`, etc. That Jinjava object can be shared across any number of threads.
