### ISSUE TITLE
TokenSymbols not customizable

### ISSUE THREAD

**Issue by KidsDontPlay** [HubSpot/jinjava#402]
Hi,
can you make the symbols cuztomizable like in [Nunjucks](https://mozilla.github.io/nunjucks/api.html#customizing-syntax). Currently they are hardcoded in `TokenScannerSymbols`.
Maybe they should be part of the `JinjavaConfig`.

**Comment by KidsDontPlay** [comment]
Or is there another way to use Jinjava and Vue at the same time.

**Comment by gabru-md** [comment]
@mattcoley close this issue?
