### ISSUE TITLE
Equalto operator doesn't work in "or" statement (== does)

### ISSUE THREAD

**Issue by Zoggy-Stardust** [HubSpot/jinjava#414]
Looks like `== `works in an `or` statement, but `equalto` doesn't. They're documented as doing the same thing [here](https://designers.hubspot.com/docs/hubl/operators-and-expression-tests#equalto), which could also be incorrect.
This doesn't work:
```
{% set myStr = 'world' %}
{% if myStr is equalto 'hey' -%}
{% elif myStr is equalto 'hello' or myStr is equalto 'world' -%}
  should work, doesn't
{% endif %}
```
this does:
```
{% set myStr = 'world' %}
{% if myStr is equalto 'hey' -%}
{% elif myStr == 'hello' or myStr == 'world' -%}
  does work
{% endif %}
```

**Comment by samukce** [comment]
hello @Zoggy-Stardust , you can find the fix here https://github.com/HubSpot/jinjava/pull/455;)

**Comment by samukce** [comment]
@Joeoh  and @mattcoley should we close this issue?

**Comment by Joeoh** [comment]
Yes thanks for resolving @samukce
