### ISSUE TITLE
Support block assignments

### ISSUE THREAD

**Issue by buremba** [HubSpot/jinjava#422]
Jinja2 supports for the following syntax out of the box:
```
{% set variable %} 
  value of the variable
{% endset %}
```

It would be nice to have support for it in jinjava as well. Please see [the docs here](https://jinja.palletsprojects.com/en/2.11.x/templates/#block-assignments).

**Comment by bhreinb** [comment]
+1 - for this construct too as it's something I would use too.

**Comment by jasmith-hs** [comment]
This functionality has been added in now
