### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by pwntester** [HubSpot/jinjava#423]
Hi,

I have identified a security vulnerability on JinJava. What would be the best way to privately report the details?

I recommend you create a private GitHub Security Advisory for this findings. This also allows you to invite me to collaborate and further discuss this findings in private before it is published.

Thanks,
A

**Comment by Stinsonr** [comment]
Hey @pwntester you can submit the details to [our bug bounty site](https://bugcrowd.com/hubspot)

**Comment by pwntester** [comment]
Actually I already did on Mar 26 (two weeks ago!!), but apparently Bugcrowd operators are getting a hard time understanding the issue. The issue reported included an issue on HubSpot use of JinJava, but also a couple of bugs in JinJava itself. Hopefully Bugcrowd operator will finally forward your the issue, otherwise, I will get in contact again to see if there is a way to report the JinJava bugs at least

**Comment by Stinsonr** [comment]
Thanks for the clarification. I see your submission now; I think it may have accidentally fallen through the cracks. I'm progressing it now. Thanks again!

**Comment by pwntester** [comment]
Cool, thanks for the status update, will close this issue then, thanks!
