### ISSUE TITLE
Problem with xmlattr filter

### ISSUE THREAD

**Issue by zepernick** [HubSpot/jinjava#43]
There seems to be a problem with the xmlattr and the way it binds itself to the filter method of the XmlAtttrFilter class.  Using this in my template:

`{{ boot_attributes_map|xmlattr }}`

Produces this error:

`com.hubspot.jinjava.interpret.FatalTemplateErrorsException: TemplateError{severity=FATAL, reason=SYNTAX_ERROR, message=TemplateSyntaxException: Method not found: class com.hubspot.jinjava.lib.filter.XmlAttrFilter.filter(com.hubspot.jinjava.objects.collections.PyMap, com.hubspot.jinjava.interpret.JinjavaInterpreter), fieldName=null, lineno=5}`

It seems like it is ignoring the String... on the method when trying to find it.  I can work around the error by sending a parameter to the xmlattr so that it finds the method:

`{{ boot_attributes_map|xmlattr('') }}`

I will see if I can identify where the problem is in the code and submit a pull request.

**Comment by jaredstehler** [comment]
Can you post a reproducible test case? We call xmlattr with no filter args in the unit test: https://github.com/HubSpot/jinjava/blob/master/src/test/java/com/hubspot/jinjava/lib/filter/XmlAttrFilterTest.java#L30

**Comment by jaredstehler** [comment]
And the version of JVM you're running as well?

**Comment by zepernick** [comment]
I will get a test case together.  I did find out that this was happening with any filter that did not have parameters passed and not just the xmlattr.  I am running jdk1.8.0_65

**Comment by jaredstehler** [comment]
Yeah I figured it wouldn't be specific to xmlattr. I'm grasping at straws but there might be some kind of conflict going on with the juel javax.el impl used in jinjava and struts/xwork...

**Comment by zepernick** [comment]
see #39 for the resolution
