### ISSUE TITLE
how to create a parsedTemplate in advance and reuse it?

### ISSUE THREAD

**Issue by childe** [HubSpot/jinjava#5]
It is same issue with https://github.com/HubSpot/jinjava/issues/4

I need custom filter and add my filters using below code
```java
        // create a node in advance and reuse it each time
	    String template = "{{some thing here}}";
	    TokenParser t =  new TokenParser(null,template);
	    Node parsedTemplate =TreeParser.parseTree(t);

		Jinjava jinjava = new Jinjava();

		Context c  = jinjava.getGlobalContext();
		c.registerFilter(f);
	
		c.putAll(event);
		
	    JinjavaInterpreter interpreter = new JinjavaInterpreter(jinjava, c, null);
	   	 
	    interpreter.render(parsedTemplate);
```

However , the event , for example ** event = {'name': "jia.liu"} ** always varies, and I must put the event to Contest c each time.

I don't want to create a Context c and register all filters to it .
But If I create Context c in advance and reuse it , will the content in the context increase continually?

In the python jinja2 , Context(named env in jinja2) is apart from event.

**Comment by childe** [comment]
i use jinjava .1.0.9

**Comment by childe** [comment]
I could create Context c for one time , and create a child of c with event.  
But another problem:  complex template like "Hello, {%if name is defined %} {{name}} {% endif %}" will raise a Exception with null as the first parameter when create TokenParser.


```java
		Map<String, Object> bindings = new HashMap<>();
		bindings.put("name", "Jared");

		Jinjava jinjava = new Jinjava();

		Context c = jinjava.getGlobalContext();
		c.registerFilter(f);
		String template = "Hello, {{name}} {% endif %}";
		TokenParser t = new TokenParser(null, template);

		Node parsedTemplate = TreeParser.parseTree(t);

		long s = System.currentTimeMillis();
		for (int i = 0; i < 10000; i++) {
			Context cc = new Context(c, bindings);

			JinjavaInterpreter interpreter = new JinjavaInterpreter(jinjava,
					cc, null);
			// Node parsedTemplate = interpreter.parse(template);

			String ss = interpreter.render(template);

		}

		System.out.println(System.currentTimeMillis() - s);
```

**Comment by jaredstehler** [comment]
So what you can do is similar to how we construct the ```JinjavaInterpreter``` instances in the ```Jinjava``` wrapper class, by creating children of the context and configs, respectively. That way, they can inherit defined filters and such without collecting unnecessary state.

```
    Context context = new Context(globalContext, bindings);

    JinjavaInterpreter parentInterpreter = JinjavaInterpreter.getCurrent();
    if(parentInterpreter != null) {
      renderConfig = parentInterpreter.getConfig();
    }

    JinjavaInterpreter interpreter = new JinjavaInterpreter(this, context, renderConfig);
    JinjavaInterpreter.pushCurrent(interpreter);
```
