### ISSUE TITLE
content.blog returning null

### ISSUE THREAD

**Issue by johnsfuller** [HubSpot/jinjava#501]
the [`{{ content.blog }}` variable](https://developers.hubspot.com/docs/cms/hubl/variables#blog-variables) used in a standard blog loop on a listings page returns null as well as outside of the loop. But `{{ group }}` returns a value. 

This is replicable across all portals so far.

**Comment by infomofo** [comment]
I'm running into a similar issue- dots within a variable name seem to not be able to be templated by the context

**Comment by jasmith-hs** [comment]
@johnsfuller I think that's just a typo in the HubL docs. (not a Jinjava issue)
`{{ content.parent_blog }}`, `{{ content_group }}`, `{{ group }}`, `{{ blog }}` are things that return the parent blog.

@infomofo You cannot have dots in a variable name as having a dot specifies that you're accessing a key's value on a dictionary.

Closing this out as there doesn't seem to be any issue with Jinjava here.
