### ISSUE TITLE
Jinjava throws UnknownTagException for escaped code

### ISSUE THREAD

**Issue by AnnaKhismatullina** [HubSpot/jinjava#505]
https://jinja.palletsprojects.com/en/2.11.x/templates/#escaping
This code doesn't work as expected:
```
{% set person = {'name':'Frank','animal':'tiger'} %}
{{ person.name }} had a {{ person.animal }}
{{ '{{ foo }} is variable syntax and {% foo %} is block syntax' }}
```

Expected: Line#3 to be rendered as is
Actual: UnknownTagException: Syntax error in '{% foo %}': Unknown tag: foo on line #1

**Comment by jasmith-hs** [comment]
You would want to turn off nested interpretation in the Jinjava Config. When it's enabled, it will try to render the nested tags after resolving the expression node.
