### ISSUE TITLE
Release of better locale support

### ISSUE THREAD

**Issue by jonathannaguin** [HubSpot/jinjava#514]
Hello,

There have been a few commits and fixes on master since a release/tag was published in MavenCentral.
I am interested on the following changes https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/lib/fn/Functions.java#L133 which are not yet released.

When can I expect a new version of the library?

Many thanks!

**Comment by rmatec** [comment]
Hi,

I also need that change. Any update on when we should expect a new release?

Thanks.

**Comment by mattcoley** [comment]
We can try to release an update today.

**Comment by phalaphone** [comment]
Released version 2.5.6
