### ISSUE TITLE
Is there a way to render class public fields?

### ISSUE THREAD

**Issue by gnaeus** [HubSpot/jinjava#587]
Example:

```java
public class User {
    public String name;
}

User user = new User();
user.name = "John";

Map<String, Object> context = new HashMap<>();
context.put("user", user);

String result = new Jinjava().render("Hello, {{user.name}}!", context);

// Hello, !
```

Tried `user.name`, `user["name"]`, `user|attr("name")` with no luck.

**Comment by gnaeus** [comment]
One possible work-around is writing custom filter like that, and then using it: `user|field("name")`

```java
public class FieldFilter implements Filter {
    @Override
    public String getName() {
        return "field";
    }

    @Override
    public Object filter(Object object, JinjavaInterpreter interpreter, String... args) {        
        if (object == null) return null;
        try {
            return object.getClass().getField(args[0]).get(object);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
}
```

**Comment by Joeoh** [comment]
You could try converting the User object to a Map<String,Object> before inserting it in the context by doing something like this 
`Map<String, Object> map = 
    mapper.convertValue(foo, new TypeReference<Map<String, Object>>() {});`

**Comment by mattcoley** [comment]
I think as long as you are using a getter it should work:
```
public class User {
 private String name;

 public String getName() {
  return name;
 }
}
```
It is generally best practice to keep your instance variables private. The object property resolver looks for the public getter methods in order to resolve `.` expressions like `user.name`.

**Comment by gnaeus** [comment]
> It is generally best practice to keep your instance variables private.

Yeah, but sometimes we don't own the code.
