### ISSUE TITLE
Possible To Skip Or Render Specific Blocks In JinJava Templates

### ISSUE THREAD

**Issue by bhreinb** [HubSpot/jinjava#618]
Hi There,

I'm wondering is it possible to skip processing of specific blocks in a JinJava template? For example

```
{% block declarations %}
{% endblock declarations %}
{% block body %}
{% endblock body %}
```
I would like to skip processing of `body` the first time around but subsequent times I would like that block to be resolved. Pretty much the exact same use case as detailed in this link

`http://atodorov.org/blog/2014/02/21/skip-or-render-specific-blocks-from-jinja2-templates/`

Many thanks in advance. Btw the library is excellent 👍

**Comment by mattcoley** [comment]
Can you surround it in `{% raw %}... {% endraw %}` tags? First process should just remove the raw tags and leave the block tags around.

**Comment by bhreinb** [comment]
Hi @mattcoley 

Thanks a mill for the quick reply. That suggestion does work.

However the snippet is user supplied, so it's dynamic in nature hence the reasoning I was asking about this...the format I was thinking would be something like this

```
{% block Variables %}
{% endblock Variables %}
{% block Payload %}
{% endblock Payload %}
```

So the user supplies both, the variables are got via the first process and the payload (JSON|XML|YAML) is de-referenced second around time...it's not desirable to de-reference everything in the first pass as the block `payload` has variables that are unknown at the time of processing...it would be a much easier process for users of this system imho to follow via a `block` approach in terms of supplying those two items rather than through the use of `raw`...however if it's not achievable through the use of `block` I guess I can workaround it.
