### ISSUE TITLE
Accessing variables in context inside a function

### ISSUE THREAD

**Issue by buremba** [HubSpot/jinjava#631]
It looks like we pass a static `Method` in `ElFunctionDefinition` in order to register custom functions. I would like to let people import JSON files via an `import(path)` function depending on the context but I'm having trouble finding the right approach as the methods need to be static.

One alternative would be requiring users to pass an extra parameter such as `import(files, "./test.json")` and injecting the `files` into the context but it seems a bit verbose and confusing so I'm wondering if the static method can access the variables in the context. 

1. Is there any way to register `Function<String, String>` instead of `Method` so that I can define an anonymous function that has access to files?

2. If not, is there any way to pass the context to the function if it's an object instance?

**Comment by jasmith-hs** [comment]
You should be able to use `JinjavaInterpreter.getCurrent().getContext()` in a static method to get the context, which you can modify.

**Comment by buremba** [comment]
@jasmith-hs that's perfect, thanks for creating this library!
