### ISSUE TITLE
range is limited to maximum 1000 elements 

### ISSUE THREAD

**Issue by ylacaute** [HubSpot/jinjava#656]
```j2
{{ range(1100) }} 
```
Give an array from 0 to 999 ! Range seems limited to 1000 elements.

I think this is a critical bug.

**Comment by ylacaute** [comment]
I tried this but still not supported by jinjava I think.
```j2
  {% range number from 3 to 6 %}
      {{ number }}
      (...)
  {% endrange %}
```

Is there a workaround ?

**Comment by ylacaute** [comment]
The limitation come from `com.hubspot.jinjava.lib.fn.Functions` :

```java
public class Functions {
  public static final int RANGE_LIMIT = 1000;
```

Why did you introduce this limitation ? I suspect this is an error just to test the RANGE_LIMIT.

**Is it possible to change it to Integer.MAX_VALUE ?**

**Comment by jboulter** [comment]
This is an intentional safety limitation to avoid unbounded iterations. I agree it would be nice to make this configurable. Would you be willing to create a PR to that effect?

**Comment by ylacaute** [comment]
I see how to update the RANGE_LIMIT and the associated unitary tests, no problem to create a PR for that.
But you spoke about making it configurable, which could be much more complicated. What kind of solution do you imagine ?

**Comment by jboulter** [comment]
here's a similar PR to add a config https://github.com/HubSpot/jinjava/pull/275

**Comment by ylacaute** [comment]
Ok thank you, I will do a PR tomorrow.

**Comment by ylacaute** [comment]
Hi, I did 2 PR :
 - #657: fix a test on master : 
 - #658: the range limit is now configurable

**Comment by ylacaute** [comment]
The PR are merged, when do you plan to do a release of it ?
This feature is critical for me now. 
Thank you.
