### ISSUE TITLE
set tag doesn't work correctly, endset is not known for javajinja

### ISSUE THREAD

**Issue by dimmonn** [HubSpot/jinjava#693]
the below setup doesn't work while it's expected to

    {% for item in items %}
    {% if item['some_prop_1'] and item['some_prop_1'] != "" %}
    {% set someAttribute %}{{item['some_prop_1']}}{% endset %}
    {% else %}

TemplateError{severity=FATAL, reason=SYNTAX_ERROR, item=OTHER, message='Error parsing '[{{item['some_prop_1']}} ]': syntax error at position 36, encountered '}', expected ':'', fieldName='}} ]', lineno=12, startPosition=36, scopeDepth=2, category=UNKNOWN, categoryErrors=null}

**Comment by mattcoley** [comment]
You should be using the set tag like `{% set someAttribute = item['some_prop_1'] %}`

**Comment by dimmonn** [comment]
Right but jinja supports the other way too that works with endset tagIn my case i can't just change because i have many templates like that already writtenSo would be good to be compliant with jinjaOn Jun 23, 2021 15:38, Matt Coley ***@***.***> wrote:
You should be using the set tag like {% set someAttribute = item['some_prop_1'] %}

**Comment by jasmith-hs** [comment]
This functionality has been added in now
