### ISSUE TITLE
"list contains item" logic doesn't work

### ISSUE THREAD

**Issue by dimmonn** [HubSpot/jinjava#701]
{% if (slot['item'] not in items) %}
    {% do slots.append(slot) %}
    {% endif %}

gives an error

TemplateError{severity=FATAL, reason=SYNTAX_ERROR, item=OTHER, message='Error parsing '(slot['item'] not in items)': syntax error at position 23, encountered 'not', expected ')'', fieldName='not in items)', lineno=14, startPosition=23, scopeDepth=2, category=UNKNOWN, categoryErrors=null}

please help to fix it

**Comment by jmaroeder** [comment]
Looks like this is a duplicate of #640
