### ISSUE TITLE
Unconsistent naming for end tags. Time for convention? 

### ISSUE THREAD

**Issue by GonzaloTorreras** [HubSpot/jinjava#717]
We are currently seeing some new tags that require to end them with `end_` while old tags are not underscored nor camelCase like `endmacro`.
Examples:
`{% endmacro %}`
`{% end_require_css %}`

Can we have a convention?

**Comment by jmaroeder** [comment]
Hi @GonzaloTorreras - I totally understand the confusion. The tags you're referring to are actually from two separate projects, though!

`endmacro`, `endif`, and the like are built-in features of [Jinja](https://jinja.palletsprojects.com/en/3.0.x/templates/). Jinjava strives to be fully-compatible with Jinja syntax, so we can't really redefine those. I believe all built-in Jinja expressions are underscore-less.

`require_css` and `require_js` are [HubL functions](https://developers.hubspot.com/docs/cms/hubl/functions). HubL is a set of extensions to jinjava - basically predefined functions, filters, etc. I believe that all HubL-defined extensions use underscores separating words.

You may want to suggest changing these on the [HubSpot Developers Slack](https://developers.hubspot.com/slack) or the [CMS Development forum](https://community.hubspot.com/t5/CMS-Development/bd-p/designers_support).
