### ISSUE TITLE
[Question] Support for Objects/Drops?

### ISSUE THREAD

**Issue by matthewrk** [HubSpot/jinjava#72]
Does this library have any support for what in Liquid is known as Drops? See here:
https://github.com/Shopify/liquid/wiki/Introduction-to-Drops

Basically its a restricted model so you can do things like {{ product.tags }}, tags being a method that grabs a bunch of tags for the product and returns them.

If this can be at minimum done by eager loading, like a JSON object, that would also solve the requirement somewhat, at least for myself.

**Comment by boulter** [comment]
There's no specialized model for this. Jinjava has access to all of the objects' methods. If you want to restrict access, you can create a DTO class that exposes only the methods/properties you want.

**Comment by matthewrk** [comment]
@boulter ok that sounds fine, is JinJava suitable to expose to end users in a SaaS setting? i.e. security / code execution wise? I know that Liquid takes special measures to make this possible but potentially that's down to Ruby's extremely dynamic nature. I can't foresee any issue with the approach you describe but would appreciate any input from a more experienced viewpoint.

**Comment by boulter** [comment]
We use Jinjava for hundreds of thousands of templates and pages at HubSpot (a SaaS company), so I'd say yes.

**Comment by matthewrk** [comment]
Ok brilliant, just making sure what I'm hoping to use it for is what its actually for. I appreciate your time answering those questions for me 👍
