### ISSUE TITLE
TemplateSyntaxException: filter method not found

### ISSUE THREAD

**Issue by matthewrk** [HubSpot/jinjava#73]
Any time I attempt to use filters I get the following error:

> Request processing failed; nested exception is com.hubspot.jinjava.interpret.FatalTemplateErrorsException: TemplateError{severity=FATAL, reason=SYNTAX_ERROR, message=TemplateSyntaxException: Method not found: class com.hubspot.jinjava.lib.filter.TitleFilter.filter(java.lang.String, com.hubspot.jinjava.interpret.JinjavaInterpreter), fieldName=null, lineno=2}

My template for that example is simply:
`{{ "hello world" | title }}`

At this point I'm not doing much so wondering if its just something I missed that's required for filter support? I'm assuming the default ones are already registered.

I was originally attempting to add my own filter but had the same problem, my filter implemented the Jinjava Filter interface as I'm sure the TitleFilter does. The method its looking for in the filter has the following footprint:

`public Object filter(Object o, JinjavaInterpreter jinjavaInterpreter, String... strings)`

I'm running on Java 1.8.0_101 with Jinjava 2.1.0.

**Comment by matthewrk** [comment]
Just realised that I was running a slightly old version of Jinjava, updated to 2.1.11 and unfortunately still having the same issue.

**Comment by boulter** [comment]
@matthewrk, this sounds like the same issue you're having. https://github.com/HubSpot/jinjava/issues/39

**Comment by matthewrk** [comment]
@boulter thanks!, it seems that it is indeed related but I can't seem to find what the conflict is.

I started a blank project with the test case from #39 and sure enough it worked, so then I copied in my dependencies for Spring Boot and it produced the error that I described above.

This is my maven file for my simple test project:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>JinJavaTest</groupId>
    <artifactId>JinJavaTest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.3.7.RELEASE</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

       <dependency>
            <groupId>com.hubspot.jinjava</groupId>
            <artifactId>jinjava</artifactId>
            <version>2.1.0</version>
        </dependency>
    </dependencies>
</project>`

And this is the dependency tree (just from mvn dependency:tree):

`[INFO] JinJavaTest:JinJavaTest:jar:1.0-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.3.7.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.3.7.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.3.7.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.3.7.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.3.7.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO] |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.21:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile
[INFO] |  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.21:compile
[INFO] |  |  +- org.springframework:spring-core:jar:4.2.7.RELEASE:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.16:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-validation:jar:1.3.7.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.36:compile
[INFO] |  |  \- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |     +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |     +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |     \- com.fasterxml:classmate:jar:1.1.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.7:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.7:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile
[INFO] |  +- org.springframework:spring-web:jar:4.2.7.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:4.2.7.RELEASE:compile
[INFO] |  |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:4.2.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-context:jar:4.2.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.2.7.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:4.2.7.RELEASE:compile
[INFO] \- com.hubspot.jinjava:jinjava:jar:2.1.0:compile
[INFO]    +- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO]    +- com.google.guava:guava:jar:17.0:compile
[INFO]    +- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO]    +- org.jsoup:jsoup:jar:1.8.1:compile
[INFO]    +- de.odysseus.juel:juel-api:jar:2.2.7:compile
[INFO]    +- de.odysseus.juel:juel-impl:jar:2.2.7:compile
[INFO]    +- de.odysseus.juel:juel-spi:jar:2.2.7:runtime
[INFO]    +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO]    \- com.google.code.findbugs:annotations:jar:3.0.0:compile
`

In that state it errors with:

> [TemplateError{severity=FATAL, reason=SYNTAX_ERROR, message=TemplateSyntaxException: Method not found: class com.hubspot.jinjava.lib.filter.UpperFilter.filter(java.lang.String, com.hubspot.jinjava.interpret.JinjavaInterpreter), fieldName=null, lineno=1}]
> 08:41:04.718 [main] DEBUG jinjava - hello {{ testvar | upper }}

But by simply moving the JinJava dependency to the top of the dependencies list, it works. That is true of both my simple test project and my main project where I originally experienced the issue. So it seems to be a conflict somewhere, I just don't know where! I can't see any shared libraries in the dependency tree.

**Comment by boulter** [comment]
My guess is it's this line:

`[INFO] | | +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.36:compile`

try excluding that.

**Comment by matthewrk** [comment]
@boulter yep that did the trick, along with org.glassfish.javax.el:3.0.0 which comes from undertow on my main project. 

I'm fairly new to Java so sorry if this is a stupid question, but these are all EL packages, which a bit of googling tells me are "Expression Language" packages. Are they all alternate implementations of the same interface? Having a hard time gauging the significance of these excludes and what exactly is happening here. Thanks for your help so far.

**Comment by boulter** [comment]
Here's some background on Java's EL. https://en.wikipedia.org/wiki/Unified_Expression_Language. Tomcat includes an implementation of EL 3.0 whereas Jinjava uses JUEL's 2.0 implementation.
