### ISSUE TITLE
Add support of recursive loops

### ISSUE THREAD

**Issue by zaycev** [HubSpot/jinjava#77]
Example from [jinja.pocoo.org/docs/dev/templates](https://jinja.pocoo.org/docs/dev/templates/):

```
<ul class="sitemap">
{%- for item in sitemap recursive %}
    <li><a href="{{ item.href|e }}">{{ item.title }}</a>
    {%- if item.children -%}
        <ul class="submenu">{{ loop(item.children) }}</ul>
    {%- endif %}</li>
{%- endfor %}
</ul>
```

**Comment by zaycev** [comment]
Or possibly, there is some other way to traverse tree structures with arbitrary depth?

**Comment by boulter** [comment]
Hi @zaycev. You can have nested for loops. Theoretically you could define a macro to iterate over a tree, but we prevent macros from calling themselves because it's too easy to create a cycle.

Jinjava do not yet support the `recursive` option on for loops, but it may not be something we want to do for the reasons mentioned above.

**Comment by joncfoo** [comment]
In case someone searches comes across this issue & is looking for a workaround... in our project we ended up duplicating the macros and ping-ponging between them to achieve the recursive effect.

May Knuth forgive us >_>

**Comment by TheWebTech** [comment]
Pinging that I would like this to be possible, or at least recursive Macros to be possible.

I tried implementing a nav using recursive macros, it appeared the server was saying "naw man, you're going down a slippery slope toward allowing infinite loops"

**Comment by jboulter** [comment]
We're pretty explicitly not allowing this. It's too easy to recurse infinitely. https://github.com/HubSpot/jinjava/pull/54

**Comment by TheWebTech** [comment]
I completely understand the reasoning, just puts devs into a bind of repeating a lot of code, resulting in it being more error prone etc.

Would a happy compromise be to only allow recursing x levels deep?

For example a use case I have is generating a menu structure(very similar to original poster)
Most of the HTML is nearly identical that I'm generating.

For a menu the maximum I could ever see someone doing this is ~9 levels deep(thinking extra wacky mega menu)

For most situations  2-3 levels of recursion would be just fine.

This would make templating easier,  as we could use recursion, but would prevent inexperienced devs from taking down whole servers.
