### ISSUE TITLE
parse shell code error: ${#array[@]}

### ISSUE THREAD

**Issue by fangjinuo** [HubSpot/jinjava#772]
${#array[@]}  => $

because the {# is  the comment start flag in jinja2

**Comment by jasmith-hs** [comment]
Many templates don't use whitespace after these tokens so this would, unfortunately, be a breaking change.

**Comment by fangjinuo** [comment]
Not all template use whitespace, some template will use it , why not add a global configuration (e.g.   withWhitespaceAfterStartToken = false) ?

**Comment by jasmith-hs** [comment]
If that is something that would work for your case, I can add it in as a [LegacyOverride](https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/LegacyOverrides.java)

**Comment by fangjinuo** [comment]
add a global configuration in LegacyOverride
