### ISSUE TITLE
Coercing of fractional numbers (0.0, 1.0) to falsy makes them hard to use

### ISSUE THREAD

**Issue by delanni** [HubSpot/jinjava#774]
I've got a use-case where I'd like to fall back to a default value of a fractional number unless it's set to something.
Imagine the following:

`// In my context: state.value = 0.5; state.otherSetting = 0.2;`

```
// In my template:
setMemoryUsage({{ state.value or 0.8 }}, {{ state.otherSetting or 0.5 }});

```

This string in the template would be interpolated to `setMemoryUsage(0.8, 0.5)`. It took me a while of debugging to see that [in the code](https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/util/ObjectTruthValue.java#L41), `Number`s are turned to integers, then compared to 0 - which makes this sort of `or` fallback in the template unusable for numbers between 0.0 - 1.0. 

Was this meant to be like this? Is there an alternative way to use these <1 fractionals in a template?

**Comment by jowiho** [comment]
This has been fixed in https://github.com/HubSpot/jinjava/commit/38eeb1f660cd6b28dcce925d64dc9112c31745d6. @delanni can you confirm that jinjava 2.7.0 fixes your problem?

**Comment by delanni** [comment]
Hi. Thanks for the fix, I no longer work at the company where this was an issue, so I can't verify.
