### ISSUE TITLE
selectattr with equalto filter is not working

### ISSUE THREAD

**Issue by derkork** [HubSpot/jinjava#78]
When I have a list of items and I want to filter them using selectattr like this

`items | selectattr('property', 'equalto', 'fixed-value')`

I'm getting the following error:

```
generate failed: TemplateError{severity=FATAL, reason=SYNTAX_ERROR, message=TemplateSyntaxException: com.hubspot.jinjava.interpret.InterpretException: equalto test requires 1 argument, fieldName=null, lineno=79}
```

But that is exactly the syntax mentioned in https://github.com/HubSpot/jinjava/blob/5e6411216131e5405af8259bfddaef61a6550ac3/src/main/java/com/hubspot/jinjava/lib/exptest/IsEqualToExpTest.java. Am I using this the wrong way or is this a bug?

**Comment by derkork** [comment]
Thanks a lot :)

**Comment by wilsbach** [comment]
I'm having this issue modifying a template in HubSpot's design manager, is there a time frame for when fixes move to the hosted platform? Documentation for the filter displays correctly, however I am receiving the error: TemplateSyntaxException: com.hubspot.jinjava.interpret.InterpretException: equalto test requires 1 argument

If this is a new issue unrelated to the above, let me know and I can open one for it.

**Comment by boulter** [comment]
@wilsbach, thanks for the reminder. The latest Jinjava is now live in HubSpot. Please give it another try.
