### ISSUE TITLE
Is `format_currency` filter supported?

### ISSUE THREAD

**Issue by al-jeyapal** [HubSpot/jinjava#784]
The documentation indicates that there is a `format_currency` filter available:
- https://developers.hubspot.com/docs/cms/hubl/filters#format-currency

This would be really helpful for some of our use cases.

However, doing the following:
```
{% set price = 100 %}
{{ price|format_currency("en-US") }}
```

Results in:
```
UnknownTokenException: Unknown token found: price|format_currency("en-US")
```

It doesn't look like anything is being registered for this filter in:
https://github.com/HubSpot/jinjava/blob/f07055439eca13a425e76412b8c33839353e46fa/src/main/java/com/hubspot/jinjava/lib/filter/FilterLibrary.java#L28

The closest thing I see in the codebase is:
https://github.com/HubSpot/jinjava/blob/f07055439eca13a425e76412b8c33839353e46fa/benchmark/src/main/java/com/hubspot/jinjava/benchmarks/liquid/Filters.java#L53

Thank you for the excellent library btw, it is a great port.

**Comment by jasmith-hs** [comment]
This filter is one that is only supported in HubL, which is an extension of Jinjava.

**Comment by al-jeyapal** [comment]
Thanks for clarifying. Happy for this to be closed out then, unless you guys are open to a PR bringing it into Jinjava?

**Comment by al-jeyapal** [comment]
No worries, thanks @jasmith-hs.
Closing out.

For anyone else's benefit, we ended up doing the following which works fine for our use case of a simple format for currency:

```
{% set price = 100 %}
{{ "%,.2f"|format(price) }}
```
