### ISSUE TITLE
Forloop???

### ISSUE THREAD

**Issue by schmitch** [HubSpot/jinjava#8]
Hello, how could I render a for loop?
I mean actually my Map("list" -> List())
will always behave strangely if i do it like that:
```
{% for item in list %}
{{ item }}
{% endfor %}
```
Item will still always be List() instead of the inner variables..

Edit: 
I sent a HashMap with a "list" -> List("1", "2", "3") object to the template the result will always be:
```List(1, 2, 3)```
But it should be:
1
2
3

Edit: it looks that the scala List is making problems..

**Comment by schmitch** [comment]
Oh god it's just that this library can't support the scala List, since that will always convert to a String instead of a correct list.

**Comment by jaredstehler** [comment]
Could be we simply need to update this method to detect the scala list type as ```Iterable```? https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/util/ObjectIterator.java#L30-L60

what is the java type of the scala list?

**Comment by schmitch** [comment]
There is no easy way to detect that.
The collection Library of scala isn't really good. So a List is a
```
sealed abstract class List[+A] extends AbstractSeq[A]
                                  with LinearSeq[A]
                                  with Product
                                  with GenericTraversableTemplate[A, List]
                                  with LinearSeqOptimized[A, List[A]]
                                  with Serializable {
```
However I found a way around that
