### ISSUE TITLE
rejectattr with equalto filter is not working

### ISSUE THREAD

**Issue by wilsbach** [HubSpot/jinjava#82]
I believe this issue is the same as issue #78, except that rejectattr is concerned. 

`topics|rejectattr("name", "equalto", "News")`

TemplateSyntaxException: com.hubspot.jinjava.interpret.InterpretException: equalto test requires 1 argument

**Comment by aliameer** [comment]
I've faced the same issue with the `rejectattr` filter.

A typical use case for the `rejectattr` filter is when one wants to "reject" the *current* blog post from a list of blog posts fetched that are to be shown in a "related blog posts" section. 

One would do, `some_blog_posts|rejectattr("absolute_url", "equalto", content.absolute_url)`

But the above produces,
**TemplateSyntaxException: com.hubspot.jinjava.interpret.InterpretException: equalto test requires 1 argument**

Of course, we can work around this using an if/unless statement as described,
http://designers.hubspot.com/tutorials/creating-a-related-post-section-with-hubl

**Comment by boulter** [comment]
Anyone interested in taking a stab at this one? It should be a similar fix as https://github.com/HubSpot/jinjava/pull/80 .
