### ISSUE TITLE
Manual whitespace control doesn't seem to work

### ISSUE THREAD

**Issue by derkork** [HubSpot/jinjava#86]
The Jinja specification allows for manual whitespace control by adding a minus at the start or end of tags (http://jinja.pocoo.org/docs/dev/templates/#whitespace-control) like:

```
{% for foo in [1,2,3,4,5,6,7,8,9] -%}
{{ foo }}
{%- endfor %}
```

This code should yield `123456789`. However it yields

```
1

2

3

4

5

6

7

8

9
```

**Comment by boulter** [comment]
It looks like we actually parse these whitespace control characters from the tag names, but they're not actually used when rendering output.

https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/tree/parse/TagToken.java#L50-L57

**Comment by derkork** [comment]
Awesome thanks a lot. Will there be a new release pushed to Maven Central with this?

**Comment by boulter** [comment]
@derkork, yup, 2.1.14 has just been released.

**Comment by derkork** [comment]
This is great, thank you very much 👍
