### ISSUE TITLE
How to ignore the dot attribute in render？

### ISSUE THREAD

**Issue by xuziheng1002** [HubSpot/jinjava#863]
I was used to fill some placeholde like "{{ person.name }}" in my template,
but it can not get current output after the render by Jinjava.
follow is the coding:

```java
public class TestCase {

    public static void main(String[] args) {
        JinjavaConfig.Builder configBuilder = JinjavaConfig.newBuilder();
        JinjavaConfig config = configBuilder.build();
        Jinjava jinjaRender = new Jinjava(config);
        Map<String, String> context = new HashMap<>();
        context.put("person.name", "jack");
        String template = "hello {{ person.name }}!";
        System.out.println(jinjaRender.render(template, context));
    }
}
```

**OUTPUT:**
```bash
hello !
```

**EXPECT OUTPUT：**
```bash
hello jack!
```

any way, is there some ways to ignore the dot-attribute on key in render?

**Comment by jasmith-hs** [comment]
You aren't able to put a variable with the name `foo.bar` onto the context in jinja so you cannot evaluate `{{ foo.bar }}`. It will always try to evaluate `bar` as being an attribute of `foo`. If you stored `contact` as a map that had a key `name`, then calling `{{ contact.name }}` would get you `jack`

**Comment by mattcoley** [comment]
To add to this programming languages will enforce a set of allowed characters for variable names including Jinjava. In this case `.` is a reserved character.

You would want to do:

```
context.put("person", ImmutableMap.of("name", "jack"));
``

**Comment by Joeoh** [comment]
To add to what @mattcoley said above, I would recommend against inserting an immutable map if you plan to allow the code to update the value later as you would hit an unsupported operation exception if you tried to update the value eg `{% set person.name = 'John' %}` . Instead do `context.put("person", Map.of("name", "jack"));`
