### ISSUE TITLE
Macro recursion broken in versions 2.1.8 and later

### ISSUE THREAD

**Issue by derkork** [HubSpot/jinjava#91]
Consider the following code:

```
{% macro example(prefix, items) %}
{{ prefix }} {{ items | first }}
{% if (items | count > 1) %}{{ example( prefix ~'-', items[1:items|count]) }}{% endif %}
{% endmacro %}

{{  example('-',['lorem', 'ipsum', 'dolor']) }}
```

With jinjava 2.1.7 or earlier this correctly outputs:

```
- lorem

-- ipsum

--- dolor
```

Starting with version 2.1.8 this no longer works and instead just outputs:

```
- lorem
```

**Comment by boulter** [comment]
@derkork, this was an intentional change in 2.1.8. See the release notes in https://github.com/HubSpot/jinjava/blob/master/CHANGES.md

**Comment by derkork** [comment]
@boulter, I understand. Could you give me some insights on why this has been removed and what could be used as a replacement functionality? Also is it possible to call macros from other macros or has this functionality also been removed?

**Comment by boulter** [comment]
@derkork you can call other macros from a macro, but you cannot have any sort of cycle, direct or indirect. 

We added this as a safety because we noticed our customers would accidentally create cycles.

A possible patch you could implement could make this behavior configurable per Jinjava instance.

**Comment by derkork** [comment]
Yeah something like a "--i-know-what-i-am-doing" flag would be nice here, e.g.:

```
JinjavaConfig.newBuilder().withMacroRecursion(true)..
```
