### ISSUE TITLE
Vulnerability in v2.6.0

### ISSUE THREAD

**Issue by shubham-arora-18** [HubSpot/jinjava#911]
We use snyk as our cloud security solution. A vulnerability in your package has been pointed out by the same. The issues details as - 

**Introduced through**: unknown:unknown@0.0.0 › com.hubspot.jinjava:jinjava@2.6.0 › com.fasterxml.jackson.dataformat:jackson-dataformat-yaml@2.7.9 › org.yaml:snakeyaml@1.15

**Overview**
[org.yaml:snakeyaml](https://code.google.com/p/snakeyaml/source/browse/) is a YAML 1.1 parser and emitter for Java.

Affected versions of this package are vulnerable to Denial of Service (DoS) due missing to nested depth limitation for collections.

**Fix**
Upgrade to org.yaml:snakeyaml@1.31

**Comment by boulter** [comment]
Thanks. Fixed with https://github.com/HubSpot/jinjava/pull/913
