### ISSUE TITLE
Is it possible to render template into native java types?

### ISSUE THREAD

**Issue by Santobert** [HubSpot/jinjava#956]
With Jinja for python it is possible to use a native environment to render template into native objects.
https://jinja.palletsprojects.com/en/3.1.x/nativetypes/

Is something similar possible with this library?

```java
Jinjava jinjava = new Jinjava();
String template = "{{ value + 2 }}";
var result = jinjava.render(template, Map.of("value", 2));
System.out.println(result); // 4
System.out.println(result.getClass().getName()); // java.lang.Integer
```

Thank you very much. Feel free to close this issue without comment if such questions are not appreciated.

**Comment by jasmith-hs** [comment]
You could do something similar using 
```
JinjavaInterpreter interpreter = jinjava.newInterpreter();
interpreter.getContext().put("value", 2);
interpreter.resolveELExpressionSilently("value + 2");
```

**Comment by Santobert** [comment]
Thank you, it works 🎉
